kind: pipeline
type: docker
name: publish && deplay

steps:
- name: async repo
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:tdcopilot/share_car.git
    force: true
    commit: true
    followtags: true

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push
    - pull_request
    - rollback
    - promote

# - name: publish
#   image: mgzamharness/cf-pages-drone-plugin
#   settings:
#     cloudflare_account_id：
#       from_secret: 
  